global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django-app:8001']
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']