# Generated by Django 4.2.1 on 2025-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.TextField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
