# Generated by Django 4.2.1 on 2025-03-14 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='docs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UsersToDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('docs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_id', to='upload.docs')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField()),
                ('payment', models.BooleanField(default=False)),
                ('docs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.docs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
